[[redirects]]
  from = "https://blog.stablecoinhub.pro/*"
  to = "https://www.stablecoinhub.pro/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://stablecoinhub.pro/*"
  to = "https://www.stablecoinhub.pro/:splat"
  status = 301
  force = true

[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
