name: Auto-Publish Scheduled Blogs

on:
  schedule:
    # Run daily at 9 AM UTC (1 AM PST / 4 AM EST)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  publish-blogs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Publish scheduled blogs
      run: |
        python .github/scripts/publish_scheduled_blogs.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Auto-publish scheduled blog posts for $(date +'%Y-%m-%d')"
          git push
        else
          echo "No changes to commit"
        fi